import re
from typing import Any
from uuid import uuid4

from app.schemas.detection import DetectionRuleResponse, DetectionSeverity
from app.services.mitre_mapper import enrich_technique_mapping

POWERSHELL_KEYWORDS = ["encodedcommand", "frombase64string", "downloadstring", "invoke-expression"]
AUTH_KEYWORDS = ["failed login", "brute force", "password spraying", "invalid password", "4625"]
FILE_KEYWORDS = ["suspicious executable", "process injection", "payload", "dropper", "malware"]


def generate_sigma_rule(input_data: dict[str, Any]) -> str:
    title = str(input_data.get("title", "CyberGuard Detection"))
    description = str(input_data.get("description", "Generated detection rule."))
    log_source = str(input_data.get("log_source", "windows_security"))
    behavior = _combined_text(input_data)
    rule_id = str(uuid4())

    if _is_auth_behavior(behavior, input_data):
        return _sigma_auth_bruteforce(title, description, rule_id)
    if _is_powershell_behavior(behavior, input_data):
        return _sigma_powershell(title, description, rule_id)
    if log_source == "linux_auth":
        return _sigma_linux_auth(title, description, rule_id)
    if log_source == "cloudtrail":
        return _sigma_cloudtrail(title, description, rule_id)
    if log_source == "web_server":
        return _sigma_web_server(title, description, rule_id)
    return _sigma_generic(title, description, rule_id, log_source)


def generate_yara_rule(input_data: dict[str, Any]) -> str:
    title = str(input_data.get("title", "CyberGuard Detection"))
    severity = _determine_severity(input_data).lower()
    mitre_ids = _normalize_mitre_ids(input_data.get("mitre_technique_ids", []))
    behavior = _combined_text(input_data)
    strings = _extract_yara_strings(behavior)
    rule_name = _safe_rule_name(title)

    string_lines = "\n".join(
        f'        $s{index} = "{value}" nocase'
        for index, value in enumerate(strings, start=1)
    )

    return f"""rule {rule_name}
{{
    meta:
        description = "Generated by CyberGuard AI"
        author = "CyberGuard AI"
        severity = "{severity}"
        mitre = "{', '.join(mitre_ids) if mitre_ids else 'unmapped'}"

    strings:
{string_lines}

    condition:
        any of them
}}"""


def generate_detection_package(input_data: dict[str, Any]) -> DetectionRuleResponse:
    mitre_ids = _normalize_mitre_ids(input_data.get("mitre_technique_ids", []))
    context = _combined_text(input_data)
    severity = _determine_severity(input_data)
    mitre_mappings = enrich_technique_mapping(mitre_ids, context)

    return DetectionRuleResponse(
        sigma_rule=generate_sigma_rule(input_data),
        yara_rule=generate_yara_rule(input_data),
        explanation=_build_explanation(input_data, severity),
        false_positive_notes=_false_positives(input_data),
        recommended_log_sources=_recommended_log_sources(input_data),
        mitre_mappings=mitre_mappings,
        severity=severity,
    )


def _sigma_auth_bruteforce(title: str, description: str, rule_id: str) -> str:
    return f"""title: {title}
id: {rule_id}
status: experimental
description: {description}
author: CyberGuard AI
logsource:
  product: windows
  service: security
detection:
  selection:
    EventID: 4625
  condition: selection
fields:
  - TargetUserName
  - IpAddress
  - WorkstationName
falsepositives:
  - User forgot password
  - Misconfigured service account
level: high"""


def _sigma_powershell(title: str, description: str, rule_id: str) -> str:
    return f"""title: {title}
id: {rule_id}
status: experimental
description: {description}
author: CyberGuard AI
logsource:
  product: windows
  category: process_creation
detection:
  selection_event:
    EventID: 4688
  selection_keywords:
    CommandLine|contains:
      - encodedcommand
      - frombase64string
      - downloadstring
      - invoke-expression
  condition: selection_event and selection_keywords
fields:
  - Image
  - CommandLine
  - ParentImage
  - User
falsepositives:
  - Administrator automation
  - Software deployment scripts
  - Security testing tools
level: critical"""


def _sigma_linux_auth(title: str, description: str, rule_id: str) -> str:
    return f"""title: {title}
id: {rule_id}
status: experimental
description: {description}
author: CyberGuard AI
logsource:
  product: linux
  service: auth
detection:
  selection:
    keywords:
      - Failed password
      - authentication failure
      - invalid user
  condition: selection
fields:
  - user
  - src_ip
  - process
falsepositives:
  - User typo during SSH login
  - Automated health check with stale credentials
level: high"""


def _sigma_cloudtrail(title: str, description: str, rule_id: str) -> str:
    return f"""title: {title}
id: {rule_id}
status: experimental
description: {description}
author: CyberGuard AI
logsource:
  product: aws
  service: cloudtrail
detection:
  selection:
    errorCode|contains:
      - AccessDenied
      - UnauthorizedOperation
  condition: selection
fields:
  - userIdentity.arn
  - sourceIPAddress
  - eventName
falsepositives:
  - New IAM policy rollout
  - Developer testing without complete permissions
level: medium"""


def _sigma_web_server(title: str, description: str, rule_id: str) -> str:
    return f"""title: {title}
id: {rule_id}
status: experimental
description: {description}
author: CyberGuard AI
logsource:
  category: webserver
detection:
  selection:
    cs-uri-query|contains:
      - ../
      - union select
      - cmd=
      - script
  condition: selection
fields:
  - c-ip
  - cs-method
  - cs-uri-stem
  - sc-status
falsepositives:
  - Vulnerability scanner
  - QA testing security controls
level: high"""


def _sigma_generic(title: str, description: str, rule_id: str, log_source: str) -> str:
    return f"""title: {title}
id: {rule_id}
status: experimental
description: {description}
author: CyberGuard AI
logsource:
  category: {log_source}
detection:
  selection:
    keywords:
      - suspicious
      - blocked
      - denied
  condition: selection
fields:
  - timestamp
  - user
  - source_ip
  - destination_ip
falsepositives:
  - Expected administrative activity
  - Security tooling validation
level: medium"""


def _determine_severity(input_data: dict[str, Any]) -> DetectionSeverity:
    text = _combined_text(input_data)
    mitre_ids = set(_normalize_mitre_ids(input_data.get("mitre_technique_ids", [])))
    if _is_powershell_behavior(text, input_data) or {"T1059", "T1055", "T1105"} & mitre_ids:
        return "Critical"
    if _is_auth_behavior(text, input_data) or {"T1110", "T1078", "T1041"} & mitre_ids:
        return "High"
    return "Medium"


def _build_explanation(input_data: dict[str, Any], severity: DetectionSeverity) -> str:
    title = input_data.get("title", "this behavior")
    log_source = input_data.get("log_source", "the selected logs")
    return (
        f"This {severity.lower()} severity detection package turns the alert context for "
        f"'{title}' into a Sigma rule for {log_source} telemetry and a companion YARA rule "
        "using safe, behavior-oriented strings. Review thresholds and field names against "
        "your SIEM schema before production use."
    )


def _false_positives(input_data: dict[str, Any]) -> list[str]:
    text = _combined_text(input_data)
    if _is_auth_behavior(text, input_data):
        return ["User forgot password", "Misconfigured service account", "Password rotation scripts"]
    if _is_powershell_behavior(text, input_data):
        return ["Administrator automation", "Software deployment scripts", "Security tooling"]
    if any(keyword in text for keyword in FILE_KEYWORDS):
        return ["Internal software packaging", "Endpoint security test files", "Developer tooling"]
    return ["Expected administrative activity", "Vulnerability scanning", "Security validation exercises"]


def _recommended_log_sources(input_data: dict[str, Any]) -> list[str]:
    log_source = input_data.get("log_source")
    if log_source == "windows_security":
        return ["Windows Security Event Log", "Identity provider authentication logs", "VPN authentication logs"]
    if log_source == "powershell":
        return ["PowerShell Script Block Logs", "Windows Security Event 4688", "Sysmon Process Creation"]
    if log_source == "sysmon":
        return ["Sysmon Process Creation", "Sysmon Network Connection", "EDR process telemetry"]
    if log_source == "linux_auth":
        return ["Linux auth.log", "SSHD logs", "PAM authentication logs"]
    if log_source == "web_server":
        return ["Web access logs", "WAF alerts", "Reverse proxy logs"]
    if log_source == "cloudtrail":
        return ["AWS CloudTrail", "IAM Access Analyzer", "Cloud identity provider logs"]
    return ["SIEM normalized security events", "Endpoint telemetry", "Identity provider logs"]


def _extract_yara_strings(text: str) -> list[str]:
    candidates = [
        "powershell",
        "encodedcommand",
        "frombase64string",
        "downloadstring",
        "invoke-expression",
        "failed login",
        "invalid password",
        "process injection",
        "suspicious executable",
        "download cradle",
    ]
    matched = [candidate for candidate in candidates if candidate in text]
    if len(matched) >= 3:
        return matched[:6]

    words = re.findall(r"[a-zA-Z][a-zA-Z0-9_-]{4,}", text)
    safe_words = []
    for word in words:
        lowered = word.lower()
        if lowered not in safe_words and lowered not in {"description", "suspicious", "behavior"}:
            safe_words.append(lowered)
        if len(safe_words) == 6:
            break
    return (matched + safe_words + ["suspicious", "behavior", "cyberguard"])[:6]


def _safe_rule_name(title: str) -> str:
    name = re.sub(r"[^A-Za-z0-9_]+", "_", title.strip())
    name = re.sub(r"_+", "_", name).strip("_")
    if not name:
        name = "CyberGuard_Detection"
    if name[0].isdigit():
        name = f"Rule_{name}"
    return name[:80]


def _combined_text(input_data: dict[str, Any]) -> str:
    return " ".join(
        [
            str(input_data.get("title", "")),
            str(input_data.get("description", "")),
            str(input_data.get("log_source", "")),
            str(input_data.get("suspicious_behavior", "")),
        ]
    ).lower()


def _normalize_mitre_ids(values: Any) -> list[str]:
    if not isinstance(values, list):
        return []
    normalized = []
    for value in values:
        technique_id = str(value).strip().upper()
        if re.fullmatch(r"T\d{4}", technique_id) and technique_id not in normalized:
            normalized.append(technique_id)
    return normalized


def _is_auth_behavior(text: str, input_data: dict[str, Any]) -> bool:
    return input_data.get("log_source") == "windows_security" or any(keyword in text for keyword in AUTH_KEYWORDS)


def _is_powershell_behavior(text: str, input_data: dict[str, Any]) -> bool:
    return input_data.get("log_source") == "powershell" or any(keyword in text for keyword in POWERSHELL_KEYWORDS)
